// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderWrite.Repository;

namespace OrderWrite.Migrations
{
    [DbContext(typeof(OrderDBContext))]
    [Migration("20191203064151_mclassone")]
    partial class mclassone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderWrite.Models.Orders", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<DateTime>("OrderDate");

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("OrderWrite.Models.Orders", b =>
                {
                    b.OwnsOne("OrderWrite.Models.CustomerName", "customer", b1 =>
                        {
                            b1.Property<int>("OrdersOrderId");

                            b1.Property<string>("FirstName");

                            b1.Property<string>("LastName");

                            b1.Property<string>("Location");

                            b1.HasKey("OrdersOrderId");

                            b1.ToTable("CustomerInfo");

                            b1.HasOne("OrderWrite.Models.Orders")
                                .WithOne("customer")
                                .HasForeignKey("OrderWrite.Models.CustomerName", "OrdersOrderId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsMany("OrderWrite.Models.OrderLineItems", "OrderItems", b1 =>
                        {
                            b1.Property<int>("OrderLineItemId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("OrderId");

                            b1.Property<int>("Price");

                            b1.Property<int>("ProductId");

                            b1.Property<int>("Quantity");

                            b1.HasKey("OrderLineItemId");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderLineItem");

                            b1.HasOne("OrderWrite.Models.Orders")
                                .WithMany("OrderItems")
                                .HasForeignKey("OrderId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
